on: [push, pull_request]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --immutable

      - name: Run ESLint
        run: npm lint

  javascript:
    name: JavaScript Transpile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --immutable

      - name: JavaScript Test
        run: npm types:check